### ISSUE TITLE
Supported Chains List

### ISSUE THREAD

**Issue by Mapoofano** [PiperFinance/CD#7]

**Comment by Mapoofano** [comment]
we are supposed to support these networks:
[ETH, BSC, Avalanche,Arbitrum,Optimism,Polygon,Moonbeam,Moonriver,Gnosis,Solana,Aurora]

**Comment by hosseinparvizi** [comment]
ChainID:
```
 1
56
43114
42161
10
137
1284
1285
100
1313161554
```
